apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
  namespace: devlopment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
      - image: 192.168.40.180/java-demo/java-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: java-demo
      imagePullSecrets:
      - name: docker-registry-auth
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
   name: demo
   namespace: devlopment
spec:
   selector:
     app: java-demo
   type: NodePort
   ports:
   - port: 31999
     targetPort: 8080
     nodePort: 31999
